### ISSUE TITLE
Feature Request: Allow Given Methods to be Task or Void

### ISSUE THREAD

**Issue by brianfeucht** [LeapingGorillaLTD/Testing#4]
Supporting this looks like it could easily follow the same pattern used for `When`.

This would allow us to avoid using the dreaded `.Result` or `.Wait()` calls in `Given`s when using BDD to write more integration style tests (like DB integration tests).  

Happy to take a stab at putting together an implementation if you are open to this change and do not have time.

**Comment by gary-lg** [comment]
Great request. Added in [Release 4.2.17](https://github.com/LeapingGorillaLTD/Testing/releases/tag/4.2.17). This is available now on [NuGet](https://www.nuget.org/packages/LeapingGorilla.Testing/4.2.17) with the same version number. If you see any problems with this in real life please open an issue.
